plugins:
  - security

rules:
  # Following recommended settings which are not yet released
  # https://github.com/nodesecurity/eslint-plugin-security/commit/eede8a4a7e0fc8d22adc0421ae96ca70fd93c53e
  security/detect-buffer-noassert: warn
  security/detect-child-process: warn
  security/detect-disable-mustache-escape: warn
  security/detect-eval-with-expression: warn
  security/detect-new-buffer: warn
  security/detect-no-csrf-before-method-override: warn
  security/detect-non-literal-fs-filename: warn
  security/detect-non-literal-regexp: warn
  security/detect-non-literal-require: warn
  security/detect-object-injection: warn
  security/detect-possible-timing-attacks: warn
  security/detect-pseudoRandomBytes: warn
  security/detect-unsafe-regex: warn
